# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/post/:title

# Setup
title:		Joselo
tagline:	'Some thoughts'
description:	'My personal blog.'
url:		http://jltorresm.github.io

author:
  name:		'Jose Torres'
  url:		https://twitter.com/jltorresmo

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/bg.jpeg #cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/jltorresmo
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/jltorresm
    desc:	Fork me on github

  - icon:	standard
    url:	http://stackoverflow.com/users/2880704/jltorresm
    desc:	Ask me on stackoverflow

  - icon:	feed
    url:	http://jltorresm.github.io/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about.html

copyright:
  author:	Joselo
  url:		http://jltorresm.github.io
  image_url: https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png #https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png
  type_url:	http://creativecommons.org/licenses/by-nc/4.0/
